# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

divisionCpp <- function(v, w, n) {
    .Call('_Knapsack_divisionCpp', PACKAGE = 'Knapsack', v, w, n)
}

